name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Выберите тест
        required: true
        default:
        type: choice
        options:
          - _min
          - _max
          - _sum
          - _mult

jobs:
  testing:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 21.0.2
        uses: actions/setup-java@v1
        with:
          java-version: '21.0.2'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: get_name 
        run: mvn clean test -Dtest = 
