name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Выберите тест, пожалуйста :)
        required: true
        default: 
        type: choice
        options:
          - min
          - max
          - sum
          - mult  

jobs:
  testing:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 21.0.2
        uses: actions/setup-java@v1
        with:
          java-version: '21.0.2'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: get_name 
        if: github.event.inputs.deployment_target != 'min' && github.event.inputs.deployment_target != 'max' 
          && github.event.inputs.deployment_target != 'sum' && github.event.inputs.deployment_target != 'mult'
        run: mvn clean test -Dtest=NumberProcessorTests 
      - name: minTest 
        if: github.event.inputs.deployment_target == 'min'
        run: mvn clean test -Dtest=NumberProcessorTests#testMin
      - name: maxTest 
        if: github.event.inputs.deployment_target == 'max'
        run: mvn clean test -Dtest=NumberProcessorTests#testMax
      - name: sumTest 
        if: github.event.inputs.deployment_target == 'sum'
        run: mvn clean test -Dtest=NumberProcessorTests#testSum
      - name: multTest 
        if: github.event.inputs.deployment_target == 'mult'
        run: mvn clean test -Dtest=NumberProcessorTests#testMult
